### ISSUE TITLE
pip 6th is not supported

### ISSUE THREAD

**Issue by signalpillar** [soulnai/gaeenv#4]
```
# create symlinks to 3rd-party requirements
gaeenv install requirements -r requirements.txt -d gaenv_lib
Traceback (most recent call last):
  File "/Users/r/.virtualenvs/demo/bin/gaeenv", line 9, in <module>
    load_entry_point('gaeenv==0.1.5', 'console_scripts', 'gaeenv')()
  File "/Users/r/.virtualenvs/demo/lib/python2.7/site-packages/gaeenv/main.py", line 36, in main
    args.func(args)
  File "/Users/r/.virtualenvs/demo/lib/python2.7/site-packages/gaeenv/main.py", line 162, in install_requirements
    req.link(args.requirements, target_dir)
  File "/Users/r/.virtualenvs/demo/lib/python2.7/site-packages/gaeenv/requirements.py", line 37, in link
    all_requirements_set = set(pip.req.parse_requirements(req_file) )
  File "/Users/r/.virtualenvs/demo/lib/python2.7/site-packages/pip/req/req_file.py", line 19, in parse_requirements
    "parse_requirements() missing 1 required keyword argument: "
TypeError: parse_requirements() missing 1 required keyword argument: 'session'
make: *** [run-gaenv] Error 1
```

**Comment by soulnai** [comment]
Fixed in https://github.com/soulnai/gaeenv/commit/858f2188437e54ac116e2d9eb9d11013c41a710a
